server:
  port: 8000

spring:
  profiles:
    active: dev
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: True

      discovery:
        locator:
          enabled: true
      routes:
      - id: server-core
        uri: lb://server-core
        predicates:
          - Path=/*/core/**
      - id: service-sms
        uri: lb://service-sms
        predicates:
          - Path=/*/sms/**
      - id: service-oss
        uri: lb://service-oss
        predicates:
          - Path=/*/oss/**